[[general]]
first="Walt"
last="Disney"
email="walt@disney.com"
skills=["drawing", "animating"]

[[experiences.first]]
title="senior animator"
start="July 1942"
end="August 1945"
description=""" First job \
  as an animator"""

[[experiences.second]]
title="lead animator"
start="February 1946"
end="January 1947"
description=""" First job \
  as a leader"""


