[information]
firstname="Walt"
lastname="Disney"
email="walt@disney.com"
phone="+3344556688"
twitter="@walt"
Title="Lead animator"

[[experiences]]
start="2015"
end="2016"
title="Lead animator"
company="Disney"
description="Lead animator on several movies"

[[experiences]]
start="2014"
end="2015"
title="Lead animator"
company="Pixar"
description="Lead animator on several movies"


[[educations]]
school="Los angeles uni."
year="2000"
title="Master degree of drawer"
description="Drawing Drawing Drawing"

[[Projects]]
name="cindirella"
description="Story of a poor girl"
url="http://cindirella.com"

[[Projects]]
name="mickey"
description="Story of a cool mouse"
url="http://mickey.com"
